version: '3'

tasks:
  install:
    desc: Install the dependencies
    cmds:
      - poetry install

  serve:
    desc: Start a development server
    aliases: [run]
    cmds:
      - task: serve:dev

  serve:dev:
    desc: Start a development server
    cmds:
      - poetry run fastapi dev sparql_file/env.py

  serve:uvicorn:
    desc: Run with uvicorn
    cmds:
      - poetry run uvicorn sparql_file.env:app --host '' --port 8080

  serve:container:
    desc: Run the container with podman
    cmds:
      - podman run -d --rm -v {{.GRAPH_FILE}}:/data/graph.ttl:z -p 8080:8080 ghcr.io/aksw/sparql-file:main

  build:
    desc: Build the container image
    cmds:
      - podman build -t sparql_file .

  format:
    desc: Format the code
    aliases: ["ruff"]
    cmds:
      - poetry run ruff format
      - poetry run ruff check --fix
